### ISSUE TITLE
is hvplot.kde() not parallel with the dask?

### ISSUE THREAD

**Issue by arm2arm** [pyviz/hvplot#158]
Hi,
Is parallelism for kde histograms implemented?
seems to me the ddf.x.hvplot.kde() is not parallel, but ddf.hvplot.hexbin with option rasterize =True is parallel .
hvplot.__version__ '0.4.0'

**Comment by philippjfr** [comment]
Correct, the kde and none of the other stats elements (like box and violin) are parallelized. Neither is hexbin, but setting rasterize=True processes the data with datashader which is parallelized and out-of-core. That said using rasterize with hexbin is not meaningful since datashader does not support hex-binning so you will get a regular aggregation that could also be achieved with ``scatter`` or ``points``.

**Comment by arm2arm** [comment]
This means the scatter and hexbin should produce similar results ?
is hist also parallel?

**Comment by philippjfr** [comment]
No, it's really just rasterize/datashade options that will make use of dask properly. There is an open issue here to use dask more internally: https://github.com/ioam/holoviews/issues/2786

The main problem is that many of the algorithms would have to be rewritten so they can be performed in parallel. Performing some of the more basic operations such as histograms shouldn't be too difficult though.

**Comment by arm2arm** [comment]
Ah ok, I see...
