### ISSUE TITLE
HeatMap options: rotation ignored using opts

### ISSUE THREAD

**Issue by rjp23** [pyviz/hvplot#169]
This does what I want and rotates the xtick labels 90 degrees:

```
a = ds.hvplot.heatmap(x='time', y='region', C='var1', rot=90)
b = ds.hvplot.heatmap(x='time', y='region', C='var2', rot=90)
c = ds.hvplot.heatmap(x='region, y='region', C='var3', rot=90)

plot =  (a + b + c)
hvplot.show(plot)
```
I thought using the .opts('HeatMap') class should work in the same way.

```
a = ds.hvplot.heatmap(x='time', y='region', C='var1')
b = ds.hvplot.heatmap(x='time', y='region', C='var2')
c = ds.hvplot.heatmap(x='region, y='region', C='var3')

plot =  (a + b + c).opts('HeatMap', dict(rot=90))
hvplot.show(plot)
```

This doesn't rotate the xtick labels.

**Comment by rjp23** [comment]
Actually it looks like none of the HeatMap options work this way. I tried "width" and that doesn't work either.

**Comment by jbednar** [comment]
Right; it doesn't work that way.  Try:

```
plot =  (a + b + c).opts('HeatMap', rot=90)
hvplot.show(plot)
```

**Comment by rjp23** [comment]
I tried that already as one of the examples suggested it should work.

> ValueError: Unexpected option 'rot' for HeatMap type across all extensions. No similar options found.

**Comment by jbednar** [comment]
Ah, here the problem is that the spelling 'rot' is taken from Panda's .plot API, but when you use .opts it uses option spellings from the underlying backend, which in this case is Bokeh.  Bokeh calls that option `xrotation`. hvplot helpfully translates from Pandas spelling to Bokeh spelling when you pass options to the .plot call, but here you are passing options to the HoloViews overlay, which no longer involves hvplot, so you need to use what HoloViews expects, which is to spell things the way Bokeh uses them.

**Comment by rjp23** [comment]
That solved it, thanks.
