### ISSUE TITLE
xsampling/ysampling in hvplot doesn't register, even though it's suggested

### ISSUE THREAD

**Issue by ahuang11** [pyviz/hvplot#60]
![image](https://user-images.githubusercontent.com/15331990/43042058-a05803ce-8d27-11e8-88fa-35da312cccd1.png)

**Comment by jbednar** [comment]
That's confusing!  It looks like the set of suggestions differs from the set of allowed keywords:

  https://github.com/pyviz/hvplot/blob/master/hvplot/converter.py#L438

I'm not sure whether the problem is that too many options are being considered for suggestion, or too few are being used, but presumably it's one of those...

**Comment by jsignell** [comment]
Just ran into this while looking at https://github.com/ioam/holoviews/issues/3037. It looks like the options are accepted but then dropped on the floor.
