### ISSUE TITLE
geopandas hvplot groupby fails

### ISSUE THREAD

**Issue by ahuang11** [pyviz/hvplot#63]
```
world = gpd.read_file(gpd.datasets.get_path('naturalearth_lowres'))
world.hvplot(width=550) + world.hvplot(groupby='continent', width=500)
```

`KeyError: "Dimension 'continent' not found."`

**Comment by ahuang11** [comment]
import geopandas as gpd
import hvplot.pandas

world = gpd.read_file(gpd.datasets.get_path('naturalearth_lowres'))
world.hvplot(groupby='continent', width=500)

```
/mnt/c/Users/sephi/GOOGLE~1/Bash/geoviews/geoviews/data/geopandas.py in validate(cls, dataset, vdims)
     81                             'coordinates but %d dimensions were found '
     82                             'which did not refer to any columns.'
---> 83                             % (type(dataset).__name__, len(geom_dims)), cls)
     84         not_found = [d.name for d in dataset.dimensions(dim_types)
     85                      if d not in geom_dims and d.name not in dataset.data]

DataError: Expected Dataset instance to declare two key dimensions corresponding to the geometry coordinates but 0 dimensions were found which did not refer to any columns.
```
new error

**Comment by jsignell** [comment]
Is this still an issue? I think `c` is the appropriate option to use in this case:

<img width="819" alt="Screen Shot 2019-06-25 at 3 44 36 PM" src="https://user-images.githubusercontent.com/4806877/60128272-3e562b80-9760-11e9-91d9-c8349fc2a493.png">

I think the original issue came up because polygons doesn't support the option groupby:

<img width="815" alt="Screen Shot 2019-06-25 at 3 46 57 PM" src="https://user-images.githubusercontent.com/4806877/60128399-8d9c5c00-9760-11e9-8dc7-683f6ba46978.png">
